version: "3.9"

services:
  gateway:
    build: ./gateway
    depends_on:
    - postgres
    - rabbitmq
    - minio
    - redis
    container_name: gateway
    ports:
      - "3000:3000"
    env_file:
      - ./gateway/.env
    volumes:
      - ./gateway:/app
      - /app/node_modules

  auth-service:
    build: ./auth-service
    depends_on:
    - postgres
    - rabbitmq
    - minio
    - redis
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  project-service:
    build: ./project-service
    depends_on:
    - postgres
    - rabbitmq
    - minio
    - redis
    container_name: project-service
    ports:
      - "3002:3002"
    env_file:
      - ./project-service/.env
    volumes:
      - ./project-service:/app
      - /app/node_modules

  task-service:
    build: ./task-service
    depends_on:
    - postgres
    - rabbitmq
    - minio
    - redis
    container_name: task-service
    ports:
      - "3003:3003"
    env_file:
      - ./task-service/.env
    volumes:
      - ./task-service:/app
      - /app/node_modules

  file-service:
    build: ./file-service
    depends_on:
    - postgres
    - rabbitmq
    - minio
    - redis
    container_name: file-service
    ports:
      - "3005:3005"
    env_file:
      - ./file-service/.env
    volumes:
      - ./file-service:/app
      - /app/node_modules

  postgres:

    image: postgres:17

    container_name: postgres

    restart: always

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: password

    ports:

      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:

    image: redis:7-alpine

    container_name: redis

    restart: always

    ports:

      - "6379:6379"

  rabbitmq:

    image: rabbitmq:4-management

    container_name: rabbitmq

    restart: always

    ports:

      - "5672:5672"

      - "15672:15672"

  minio:

    image: minio/minio

    container_name: minio

    command: server /data --console-address ":9001"

    environment:

      MINIO_ROOT_USER: minioadmin

      MINIO_ROOT_PASSWORD: minioadmin

    ports:

      - "9000:9000"

      - "9001:9001"

    volumes:

      - minio_data:/data

volumes:

  postgres_data:

  minio_data:

